### ISSUE TITLE
Не останавливайся

### ISSUE THREAD

**Issue by Butonix** [devilstars/openDTF#1]
Могу поддержать материально, если проект будет развиваться!
Очень жду...

**Comment by devilstars** [comment]
Спасибо за интерес!
Не могу обещать, что процесс будет идти быстро. Всё же я этим занимаюсь только в свободное время вне основной работы.
Но, по крайней мере, я стараюсь делать хорошо :)

**Comment by Butonix** [comment]
> Спасибо за интерес!
> Не могу обещать, что процесс будет идти быстро. Всё же я этим занимаюсь только в свободное время вне основной работы.
> Но, по крайней мере, я стараюсь делать хорошо :)

@devilstars Посмотрите в сторону next.js или nuxt
Так как они имеют встроенный рендеринг. Чтоб проблем с seo не было.
У вас в планах довести проект до конца?

**Comment by devilstars** [comment]
По поводу nuxt или любому другому ssr - сейчас качество ботов поисковых систем такое, что они спокойно видят весь контент без какого-либо пререндера. Проверено на клиентских проектах. 
В плане сео проблем не будет, минимальный достаточный набор мета данных всегда будет на всех страницах. 
ps: да, проект будет доведён какого-то стабильного состояния, но это не значит, что разработка остановится :)

**Comment by Butonix** [comment]
> По поводу nuxt или любому другому ssr - сейчас качество ботов поисковых систем такое, что они спокойно видят весь контент без какого-либо пререндера. Проверено на клиентских проектах.
> В плане сео проблем не будет, минимальный достаточный набор мета данных всегда будет на всех страницах.
> ps: да, проект будет доведён какого-то стабильного состояния, но это не значит, что разработка остановится :)

Больше не будете продолжать?🙁
